name: aiza
description: Product localisation app

# Flutter SDK constraints
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2  # iOS-style icons

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true